#!/usr/bin/env python3
import sys
from pathlib import Path

# ==============================================================================
# VFS GENERATOR (Virtual File System)
# Converts a directory tree into a zero-overhead C++ header with static byte arrays.
# This ensures safe, binary-compatible embedding of resources (Lua, GLSL, Images).
# ==============================================================================

def generate_vfs(source_dir: str, output_file: str):
    source_path = Path(source_dir)
    
    arrays_cpp = []
    entries_cpp = []
    
    for filepath in sorted(source_path.rglob('*')):
        if not filepath.is_file():
            continue
            
        rel_path = filepath.relative_to(source_path).as_posix()
        var_name = "file_" + "".join(c if c.isalnum() else "_" for c in rel_path)
        
        try:
            data = filepath.read_bytes()
            hex_bytes = [f"0x{b:02x}" for b in data] + ["0x00"]
            
            chunks = [", ".join(hex_bytes[i:i+16]) for i in range(0, len(hex_bytes), 16)]
            formatted_hex = ",\n        ".join(chunks)
            
            arrays_cpp.append(f"    inline constexpr unsigned char {var_name}[] = {{\n        {formatted_hex}\n    }};")
            
            entries_cpp.append(
                f'        VirtualFile{{"{rel_path}", '
                f'std::string_view(reinterpret_cast<const char*>({var_name}), {len(data)})}}'
            )
            
        except Exception as e:
            print(f"Skipping unreadable file: {rel_path} - {e}")
            sys.exit(1)

    # Note: joined with ",\n" to correctly format the C++ array
    entries_joined = ",\n".join(entries_cpp)

    cpp_template = f"""// AUTO-GENERATED VIRTUAL FILE SYSTEM
// Do not edit manually. Generated by utilities/embed_fs.py
#pragma once

#include <string_view>
#include <optional>
#include <array>

namespace EmbeddedFS {{

// ==============================================================================
// 1. FILE DATA (Static Hex Arrays in .rodata)
// ==============================================================================
{chr(10).join(arrays_cpp)}

// ==============================================================================
// 2. VFS METADATA & LOOKUP
// ==============================================================================
    struct VirtualFile {{
        std::string_view path;
        std::string_view content;
    }};

    // Array is 'const', not 'constexpr', because reinterpret_cast is used.
    inline const std::array<VirtualFile, {len(entries_cpp)}> Files = {{
{entries_joined}
    }};

    // O(N) Linear Search. Extremely fast for < 256 items due to L1 cache locality.
    inline std::optional<std::string_view> get_file(std::string_view path) {{
        for (const auto& file : Files) {{
            if (file.path == path) return file.content;
        }}
        return std::nullopt;
    }}

}} // namespace EmbeddedFS
"""

    output_path = Path(output_file)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(cpp_template, encoding='utf-8')
    print(f"VFS Successfully generated: {output_file} ({len(entries_cpp)} files baked)")

if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Usage: python3 embed_fs.py <source_directory> <output_header.hpp>")
        sys.exit(1)
        
    generate_vfs(sys.argv[1], sys.argv[2])