// --- Auto-generated by generate_plugin.py ---
#ifndef SOLID_BG_HPP
#define SOLID_BG_HPP

#include "wallpaper-effect.hpp"
#include <GLES3/gl3.h>
#include <glm/glm.hpp>
#include <string>
#include <vector>

class SolidBgEffect : public WallpaperEffect {
public:
    SolidBgEffect();
    ~SolidBgEffect() override;

    // --- WallpaperEffect Interface ---
    const char* get_name() const override;
    std::vector<EffectParameter> get_parameters() const override;
    void set_parameter(const std::string& name, const EffectParameterValue& value) override;

    bool initialize(ICoreContext* core, uint32_t width, uint32_t height) override;
    void render(uint32_t width, uint32_t height, float dt) override;
    void cleanup() override;

private:
    GLuint program = 0;
    GLuint vao = 0;
    float time = 0.0f;
    ICoreContext* m_core = nullptr;

    // --- Parameter Member Variables ---
    int gradient_type = 3;
    int color_space = 1;
    glm::vec3 color_1 = glm::vec3(0.89f, 0.28f, 0.20f);
    glm::vec3 color_2 = glm::vec3(0.15f, 0.40f, 0.85f);
    glm::vec3 color_3 = glm::vec3(0.95f, 0.75f, 0.20f);
    glm::vec3 color_4 = glm::vec3(0.60f, 0.20f, 0.80f);
    float angle = 45.0;
    glm::vec2 radial_center = glm::vec2(0.5f, 0.5f);
    float radial_radius = 1.2;
    float dither_strength = 1.0;

    // --- Texture State Variables ---


    // --- Uniform Locations ---
    GLuint u_time = 0;
    GLuint u_resolution = 0;
    GLuint u_gradient_type = 0;
    GLuint u_color_space = 0;
    GLuint u_color_1 = 0;
    GLuint u_color_2 = 0;
    GLuint u_color_3 = 0;
    GLuint u_color_4 = 0;
    GLuint u_angle = 0;
    GLuint u_radial_center = 0;
    GLuint u_radial_radius = 0;
    GLuint u_dither_strength = 0;


};

#endif // SOLID_BG_HPP