// --- Auto-generated by ShaderDesk Plugin Generator ---
#include "solid-bg.hpp"
#include "shader-utils.hpp" // ShaderDesk SDK utilities
#include <iostream>
#include <stdexcept>



// ==============================================================================
// DEVELOPER GUIDE: EXTENDING THIS PLUGIN
// ==============================================================================
// This auto-generated file is just a starting point! You are encouraged to modify 
// it and add your own complex C++ logic.
//
// Why write C++ logic here instead of using Lua or GLSL?
// 1. High-Performance Math: Simulating physics (e.g., Boids, particles, fluid dynamics) 
//    or generating procedural 3D meshes (like fractals) is too slow for Lua.
// 2. BlackBoard Integration: Use `core->get_blackboard()` to read zero-latency 
//    data streams from background daemons (e.g., Audio FFT bands, raw mouse inputs).
// 3. Advanced OpenGL: You are not limited to a fullscreen triangle! You can load 
//    textures, create Framebuffer Objects (FBOs), or dispatch Compute Shaders here.
// ==============================================================================

SolidBgEffect::SolidBgEffect() = default;

SolidBgEffect::~SolidBgEffect() {
    on_cleanup();
}

const char* SolidBgEffect::get_name() const {
    return "Solid Bg";
}

// ------------------------------------------------------------------------------
// PARAMETER MANAGEMENT
// Exposes parameters to the Lua configuration engine.
// ------------------------------------------------------------------------------
std::vector<EffectParameter> SolidBgEffect::get_parameters() const {
    return {
        {"gradient_type", "0: Solid, 1: Linear, 2: Radial, 3: 4-Corner Mesh", gradient_type},
        {"color_space", "0: sRGB (Standard), 1: Oklab (Perceptual smooth blending)", color_space},
        {"color_1", "Primary Color (Top-Left)", color_1},
        {"color_2", "Secondary Color (Bottom-Right)", color_2},
        {"color_3", "Tertiary Color (Top-Right / Mesh only)", color_3},
        {"color_4", "Quaternary Color (Bottom-Left / Mesh only)", color_4},
        {"angle", "Angle in degrees (Linear only)", angle},
        {"radial_center", "Center position (Radial only)", radial_center},
        {"radial_radius", "Gradient spread radius (Radial only)", radial_radius},
        {"dither_strength", "TPDF Dithering intensity (1.0 = smooth 8-bit)", dither_strength},
    };
}

void SolidBgEffect::set_parameter(const std::string& name, const EffectParameterValue& value) {
    try {
        if (name == "gradient_type") {
            gradient_type = std::get<int>(value);
        }
        else if (name == "color_space") {
            color_space = std::get<int>(value);
        }
        else if (name == "color_1") {
            color_1 = std::get<glm::vec3>(value);
        }
        else if (name == "color_2") {
            color_2 = std::get<glm::vec3>(value);
        }
        else if (name == "color_3") {
            color_3 = std::get<glm::vec3>(value);
        }
        else if (name == "color_4") {
            color_4 = std::get<glm::vec3>(value);
        }
        else if (name == "angle") {
            angle = std::get<float>(value);
        }
        else if (name == "radial_center") {
            radial_center = std::get<glm::vec2>(value);
        }
        else if (name == "radial_radius") {
            radial_radius = std::get<float>(value);
        }
        else if (name == "dither_strength") {
            dither_strength = std::get<float>(value);
        }
        else {
             std::cerr << "Warning: Unknown parameter '" << name << "'." << std::endl;
        }
    } catch (const std::bad_variant_access& e) {
        std::cerr << "[" << get_name() << "] Warning: Type mismatch for parameter '" 
                  << name << "'. " << e.what() << std::endl;
    }
}

// ------------------------------------------------------------------------------
// INITIALIZATION & SHADER COMPILATION
// ------------------------------------------------------------------------------
bool SolidBgEffect::initialize(ICoreContext* core, uint32_t width, uint32_t height) {
    m_core = core;

    // 1. Load shaders from the plugin bundle directory.
    std::string vert_src = shader_utils::load_shader_source(core, get_name(), "solid_vert.glsl");
    std::string frag_src = shader_utils::load_shader_source(core, get_name(), "solid_frag.glsl");
    
    if (vert_src.empty() || frag_src.empty()) {
        std::cerr << "[" << get_name() << "] CRITICAL: Failed to load shader files from bundle!" << std::endl;
        return false;
    }

    program = shader_utils::create_shader_program(vert_src, frag_src);
    if (!program) {
        std::cerr << "[" << get_name() << "] CRITICAL: Shader program linking failed!" << std::endl;
        return false;
    }
    
    // 2. Cache uniform locations
    u_time = glGetUniformLocation(program, "time");
    u_resolution = glGetUniformLocation(program, "resolution");
    u_gradient_type = glGetUniformLocation(program, "gradient_type");
    u_color_space = glGetUniformLocation(program, "color_space");
    u_color_1 = glGetUniformLocation(program, "color_1");
    u_color_2 = glGetUniformLocation(program, "color_2");
    u_color_3 = glGetUniformLocation(program, "color_3");
    u_color_4 = glGetUniformLocation(program, "color_4");
    u_angle = glGetUniformLocation(program, "angle");
    u_radial_center = glGetUniformLocation(program, "radial_center");
    u_radial_radius = glGetUniformLocation(program, "radial_radius");
    u_dither_strength = glGetUniformLocation(program, "dither_strength");

    // 3. Create an empty VAO.
    // We use the "Zero-VBO Fullscreen Triangle" technique.
    glGenVertexArrays(1, &vao);
    
    std::cout << "[" << get_name() << "] Initialized successfully (Resolution: " 
              << width << "x" << height << ")." << std::endl;
    return true;
}



// ------------------------------------------------------------------------------
// MAIN RENDER LOOP
// Called by the Wayland compositor core every frame (e.g., 60 or 144 times/sec).
// ------------------------------------------------------------------------------
void SolidBgEffect::render(uint32_t width, uint32_t height, float dt) {


    glUseProgram(program);
    
    // Use the real time delta provided by the Wayland compositor for smooth animation
    time += dt; 
    
    if (u_time != -1) glUniform1f(u_time, time);
    if (u_resolution != -1) glUniform2f(u_resolution, static_cast<float>(width), static_cast<float>(height));
    
    // Apply auto-generated uniform variables from Lua configuration
    if (u_gradient_type != -1) glUniform1i(u_gradient_type, gradient_type);
    if (u_color_space != -1) glUniform1i(u_color_space, color_space);
    if (u_color_1 != -1) glUniform3fv(u_color_1, 1, &color_1[0]);
    if (u_color_2 != -1) glUniform3fv(u_color_2, 1, &color_2[0]);
    if (u_color_3 != -1) glUniform3fv(u_color_3, 1, &color_3[0]);
    if (u_color_4 != -1) glUniform3fv(u_color_4, 1, &color_4[0]);
    if (u_angle != -1) glUniform1f(u_angle, angle);
    if (u_radial_center != -1) glUniform2fv(u_radial_center, 1, &radial_center[0]);
    if (u_radial_radius != -1) glUniform1f(u_radial_radius, radial_radius);
    if (u_dither_strength != -1) glUniform1f(u_dither_strength, dither_strength);

    // Bind textures and resolutions


    // Disable depth testing for 2D/Background effects to prevent Z-fighting
    glDisable(GL_DEPTH_TEST);

    glBindBuffer(GL_ARRAY_BUFFER, 0);

    // Draw the fullscreen triangle using the empty VAO
    glBindVertexArray(vao);
    glDrawArrays(GL_TRIANGLES, 0, 3);
    
    glBindVertexArray(0);
    glActiveTexture(GL_TEXTURE0);

    // Restore depth testing for subsequent 3D layers in the rendering pipeline
    glEnable(GL_DEPTH_TEST);
}

// ------------------------------------------------------------------------------
// RESOURCE CLEANUP
// ------------------------------------------------------------------------------
void SolidBgEffect::on_cleanup() {
    if (program) {
        glDeleteProgram(program);
        program = 0;
    }
    if (vao) {
        glDeleteVertexArrays(1, &vao);
        vao = 0;
    }

}

// ==============================================================================
// C-ABI EXPORTS (Plugin Manager Entry Points)
// ==============================================================================
extern "C" {
    uint32_t get_abi_version() {
        return SHADER_DESK_ABI_VERSION;
    }
    
    IWallpaperEffectABI* create_effect() {
        return new SolidBgEffect();
    }

    void destroy_effect(IWallpaperEffectABI* effect) {
        delete static_cast<SolidBgEffect*>(effect);
    }
}