// --- Auto-generated by generate_plugin.py ---
#include "test_gen.hpp"
#include "shader-utils.hpp" // Common helpers
#include <iostream>
#include <stdexcept>

TestGenEffect::TestGenEffect() = default;
TestGenEffect::~TestGenEffect() {
    cleanup();
}

const char* TestGenEffect::get_name() const {
    return "Test_Gen";
}

std::vector<EffectParameter> TestGenEffect::get_parameters() const {
    return {
        {"oscill_amp", "Амплитуда базовых колебаний.", oscill_amp},
        {"oscill_freq", "Частота базовых колебаний.", oscill_freq},
        {"wave_amp", "Амплитуда волнового эффекта.", wave_amp},
        {"wave_freq", "Частота (плотность) волн на поверхности.", wave_freq},
        {"twist_amp", "Сила эффекта скручивания.", twist_amp},
        {"pulse_amp", "Амплитуда базовой пульсации.", pulse_amp},
        {"noise_amp", "Амплитуда шумовой деформации.", noise_amp},
        {"sphere_scale", "Общий масштаб сферы.", sphere_scale},
        {"audio_bass", "Текущий уровень басов.", audio_bass},
        {"audio_mid", "Текущий уровень средних частот.", audio_mid},
        {"audio_treble", "Текущий уровень высоких частот.", audio_treble},
    };
}

void TestGenEffect::set_parameter(const std::string& name, const EffectParameterValue& value) {
    try {
        if (name == "oscill_amp") {
            oscill_amp = std::get<float>(value);
        }
        else if (name == "oscill_freq") {
            oscill_freq = std::get<float>(value);
        }
        else if (name == "wave_amp") {
            wave_amp = std::get<float>(value);
        }
        else if (name == "wave_freq") {
            wave_freq = std::get<float>(value);
        }
        else if (name == "twist_amp") {
            twist_amp = std::get<float>(value);
        }
        else if (name == "pulse_amp") {
            pulse_amp = std::get<float>(value);
        }
        else if (name == "noise_amp") {
            noise_amp = std::get<float>(value);
        }
        else if (name == "sphere_scale") {
            sphere_scale = std::get<float>(value);
        }
        else if (name == "audio_bass") {
            audio_bass = std::get<float>(value);
        }
        else if (name == "audio_mid") {
            audio_mid = std::get<float>(value);
        }
        else if (name == "audio_treble") {
            audio_treble = std::get<float>(value);
        }
        else {
             std::cerr << "Warning: Unknown parameter '" << name << "'." << std::endl;
        }
    } catch (const std::bad_variant_access& e) {
        std::cerr << "Warning: Type mismatch for parameter '" << name << "'. " << e.what() << std::endl;
    }
}

bool TestGenEffect::initialize(uint32_t width, uint32_t height) {
    // Note: shader_utils expects shader names relative to a common shader directory
    std::string vert_src = shader_utils::load_shader_source("test_gen/sphere_vert.glsl");
    std::string frag_src = shader_utils::load_shader_source("test_gen/sphere_frag.glsl");
    if (vert_src.empty() || frag_src.empty()) return false;

    program = shader_utils::create_shader_program(vert_src, frag_src);
    if (!program) return false;
    
    // Get uniform locations
    u_time = glGetUniformLocation(program, "time");
    u_resolution = glGetUniformLocation(program, "resolution");
    u_oscill_amp = glGetUniformLocation(program, "oscill_amp");
    u_oscill_freq = glGetUniformLocation(program, "oscill_freq");
    u_wave_amp = glGetUniformLocation(program, "wave_amp");
    u_wave_freq = glGetUniformLocation(program, "wave_freq");
    u_twist_amp = glGetUniformLocation(program, "twist_amp");
    u_pulse_amp = glGetUniformLocation(program, "pulse_amp");
    u_noise_amp = glGetUniformLocation(program, "noise_amp");
    u_sphere_scale = glGetUniformLocation(program, "sphere_scale");
    u_audio_bass = glGetUniformLocation(program, "audio_bass");
    u_audio_mid = glGetUniformLocation(program, "audio_mid");
    u_audio_treble = glGetUniformLocation(program, "audio_treble");

    // Setup VAO for a fullscreen quad/triangle
    glGenVertexArrays(1, &vao);
    glBindVertexArray(vao);
    
    std::cout << "'Test_Gen' initialized." << std::endl;
    return true;
}

void TestGenEffect::render(uint32_t width, uint32_t height) {
    glUseProgram(program);
    
    time += 0.016f; // Assume ~60 FPS
    glUniform1f(u_time, time);
    glUniform2f(u_resolution, static_cast<float>(width), static_cast<float>(height));
    
    // Set parameter uniforms
    glUniform1f(u_oscill_amp, oscill_amp);
    glUniform1f(u_oscill_freq, oscill_freq);
    glUniform1f(u_wave_amp, wave_amp);
    glUniform1f(u_wave_freq, wave_freq);
    glUniform1f(u_twist_amp, twist_amp);
    glUniform1f(u_pulse_amp, pulse_amp);
    glUniform1f(u_noise_amp, noise_amp);
    glUniform1f(u_sphere_scale, sphere_scale);
    glUniform1f(u_audio_bass, audio_bass);
    glUniform1f(u_audio_mid, audio_mid);
    glUniform1f(u_audio_treble, audio_treble);

    // Draw a fullscreen triangle (no VBO needed)
    glBindVertexArray(vao);
    glDrawArrays(GL_TRIANGLES, 0, 3);
    glBindVertexArray(0);
}

void TestGenEffect::cleanup() {
    if (program) glDeleteProgram(program);
    if (vao) glDeleteVertexArrays(1, &vao);
    program = 0;
    vao = 0;
}

void TestGenEffect::handle_pointer_motion(double dx, double dy, bool is_touchpad) {
    // Implement if needed by the shader
}

// --- Exported C functions for the plugin system ---
extern "C" {
    WallpaperEffect* create_effect() {
        return new TestGenEffect();
    }

    void destroy_effect(WallpaperEffect* effect) {
        delete effect;
    }
}