// --- Auto-generated by generate_plugin.py ---
#ifndef TEST_GEN_HPP
#define TEST_GEN_HPP

#include "wallpaper-effect.hpp"
#include <GLES3/gl3.h>
#include <glm/glm.hpp>
#include <string>
#include <vector>

class TestGenEffect : public WallpaperEffect {
public:
    TestGenEffect();
    ~TestGenEffect() override;

    // --- WallpaperEffect Interface ---
    const char* get_name() const override;
    std::vector<EffectParameter> get_parameters() const override;
    void set_parameter(const std::string& name, const EffectParameterValue& value) override;

    bool initialize(uint32_t width, uint32_t height) override;
    void render(uint32_t width, uint32_t height) override;
    void cleanup() override;
    void handle_pointer_motion(double dx, double dy, bool is_touchpad) override;

private:
    GLuint program = 0;
    GLuint vao = 0;
    float time = 0.0f;

    // --- Parameter Member Variables ---
    float oscill_amp = 0.0;
    float oscill_freq = 1.0;
    float wave_amp = 0.0;
    float wave_freq = 10.0;
    float twist_amp = 0.0;
    float pulse_amp = 0.0;
    float noise_amp = 0.0;
    float sphere_scale = 1.0;
    float audio_bass = 0.0;
    float audio_mid = 0.0;
    float audio_treble = 0.0;

    // --- Uniform Locations ---
    GLuint u_time = 0;
    GLuint u_resolution = 0;
    GLuint u_oscill_amp = 0;
    GLuint u_oscill_freq = 0;
    GLuint u_wave_amp = 0;
    GLuint u_wave_freq = 0;
    GLuint u_twist_amp = 0;
    GLuint u_pulse_amp = 0;
    GLuint u_noise_amp = 0;
    GLuint u_sphere_scale = 0;
    GLuint u_audio_bass = 0;
    GLuint u_audio_mid = 0;
    GLuint u_audio_treble = 0;
};

#endif // TEST_GEN_HPP