-- ~/.config/interactive-wallpaper/ctl.lua
-- Auxiliary Lua module for remote control via the 'shader-desk-ctl' CLI utility.

local ctl = {}

-- ==============================================================================
-- CORE HELPERS
-- ==============================================================================

-- Applies an action to a specific output, or to all outputs if "*" is provided.
local function with_target(output_name, action)
    if not output_name or output_name == "*" or output_name == "" then
        for name, out in pairs(core.outputs) do
            action(name, out)
        end
    else
        if core.outputs[output_name] then
            action(output_name, core.outputs[output_name])
        end
    end
end

-- Safely resolves the primary semantic tag of an output if none is explicitly provided.
local function get_primary_tag(out)
    if out.layers and out.layers[1] then
        return out.layers[1].tag or out.layers[1].effect
    end
    return nil
end

-- Deep comparison helper (useful for comparing {R, G, B} color tables).
local function is_equal(a, b)
    if type(a) ~= type(b) then return false end
    if type(a) == "table" then
        if #A ~= #B then return false end
        for k, v in pairs(a) do
            if not is_equal(v, b[k]) then return false end
        end
        return true
    end
    return a == b
end

-- ==============================================================================
-- 1. SMART PARAMETER CONTROL (Fluent API Based)
-- ==============================================================================

-- Set a specific parameter.
-- Example: shader-desk-ctl "ctl.set('sphere_scale', 1.5, '*', 'Hilbert Cube')"
function ctl.set(param, value, output, tag)
    with_target(output, function(name, out)
        local target_tag = tag or get_primary_tag(out)
        if target_tag then
            core.get_layer(name, target_tag):set(param, value)
        end
    end)
end

-- Toggle a boolean parameter (e.g., true -> false).
-- Example: shader-desk-ctl "ctl.toggle('enable_stripes')"
function ctl.toggle(param, output, tag)
    with_target(output, function(name, out)
        local target_tag = tag or get_primary_tag(out)
        if target_tag then
            local layer = core.get_layer(name, target_tag)
            local current = layer:get(param)
            if current ~= nil then
                layer:set(param, not current)
            end
        end
    end)
end

-- Cycle through a list of values. Supports colors (tables) and strings.
-- Example: shader-desk-ctl "ctl.cycle('bg_color', {{1,0,0}, {0,1,0}, {0,0,1}})"
function ctl.cycle(param, values_list, output, tag)
    with_target(output, function(name, out)
        local target_tag = tag or get_primary_tag(out)
        if target_tag then
            local layer = core.get_layer(name, target_tag)
            local current = layer:get(param)
            
            local next_idx = 1
            for i, val in ipairs(values_list) do
                if is_equal(val, current) then
                    next_idx = (i % #values_list) + 1
                    break
                end
            end
            layer:set(param, values_list[next_idx])
        end
    end)
end

-- Apply a preset to a layer on the fly.
-- Example: shader-desk-ctl "ctl.preset('Icosahedron Sphere', 'cyberpunk')"
function ctl.preset(effect_name, preset_name, output)
    with_target(output, function(name, out)
        -- Fallback to the old logic since presets apply to the entire layer configuration table
        if core.utils.apply_preset and out.settings then
            core.utils.apply_preset(out.settings, effect_name, preset_name)
            
            local target_tag = get_primary_tag(out)
            if target_tag then
                local layer = core.get_layer(name, target_tag)
                for k, v in pairs(out.settings) do
                    layer:set(k, v)
                end
            end
        end
    end)
end

-- ==============================================================================
-- 2. THEMING & UNIXPORN INTEGRATION
-- ==============================================================================

-- Automatically load and apply the color palette generated by Pywal.
-- Example: shader-desk-ctl "ctl.pywal()"
function ctl.pywal(output)
    local wal_file = os.getenv("HOME") .. "/.cache/wal/colors.json"
    local f = io.open(wal_file, "r")
    if not f then 
        print("Pywal colors.json not found!") 
        return 
    end
    local content = f:read("*all")
    f:close()

    local function hex_to_rgb(hex)
        hex = hex:gsub("#", "")
        return {
            tonumber("0x" .. hex:sub(1, 2)) / 255.0,
            tonumber("0x" .. hex:sub(3, 4)) / 255.0,
            tonumber("0x" .. hex:sub(5, 6)) / 255.0
        }
    end

    local bg_hex = content:match('"color0": "%s*(#[%a%d]+)')
    local fg_hex = content:match('"color7": "%s*(#[%a%d]+)')
    local accent_hex = content:match('"color5": "%s*(#[%a%d]+)')

    if bg_hex and accent_hex then
        ctl.set("background_color", hex_to_rgb(bg_hex), output)
        ctl.set("wireframe_color", hex_to_rgb(accent_hex), output)
        ctl.set("curve_color", hex_to_rgb(accent_hex), output)
        print("Successfully applied Pywal palette!")
    end
end

-- Switch between light and dark themes manually.
-- Example: shader-desk-ctl "ctl.theme('dark')"
function ctl.theme(mode, output)
    if mode == "dark" then
        ctl.set("background_color", {0.05, 0.05, 0.08}, output)
    elseif mode == "light" then
        ctl.set("background_color", {0.85, 0.90, 0.95}, output)
    end
end




-- ==============================================================================
-- 3. POWER MANAGEMENT & DATA PROVIDERS
-- ==============================================================================

-- Enable or disable a Data Provider (e.g., turn off audio reaction during a Zoom call).
-- Example: shader-desk-ctl "ctl.provider('Native FFTW Audio Provider', false)"
function ctl.provider(name, enabled)
    if core.providers[name] then
        core.providers[name].enabled = enabled
        print("Provider " .. name .. " enabled: " .. tostring(enabled))
    end
end

-- "Gaming Mode" or battery saver. Completely stops the C++ render loop (0% GPU/CPU).
-- Example: shader-desk-ctl "ctl.freeze(true)"
function ctl.freeze(state)
    if core._is_frozen == state then return end
    core._is_frozen = state 
    
    if core.pause_render then
        core.pause_render(state)
        
        -- Anti-Jump Mechanism:
        -- The mouse daemon keeps accumulating coordinates even while the screen is frozen.
        -- When we wake up, we must sync the Lua camera state with the new mouse position 
        -- so the camera doesn't violently snap/spin on the very first frame.
        if not state then
            for name, out in pairs(core.outputs) do
                if out.state then
                    out.state.last_mx = core.get_float("mouse.accum_x", 0.0)
                    out.state.last_my = core.get_float("mouse.accum_y", 0.0)
                end
            end
        end
    end
end

-- ==============================================================================
-- 4. INTERACTIVE EVENTS & NOTIFICATIONS
-- ==============================================================================

-- Temporarily flashes the wallpaper color (e.g., when receiving a Dunst/Mako notification).
-- Example: shader-desk-ctl "ctl.flash({1.0, 0.0, 0.0}, 0.5)" (flash red for 500ms)
function ctl.flash(flash_color, duration_sec, output, tag)
    with_target(output, function(name, out)
        local target_tag = tag or get_primary_tag(out)
        if target_tag then
            local layer = core.get_layer(name, target_tag)
            
            local target_param = "wireframe_color"
            local orig_color = layer:get(target_param)
            if orig_color == nil then
                target_param = "curve_color"
                orig_color = layer:get(target_param)
            end
            if orig_color == nil then return end 
            
            layer:set(target_param, flash_color)
            
            -- Correct, deterministic timer stop with ID closure
            local timer_id
            timer_id = core.set_interval(math.floor(duration_sec * 1000), function()
                layer:set(target_param, orig_color)
                if timer_id then
                    core.clear_interval(timer_id) -- Safely release the descriptor in the Linux kernel
                end
            end)
        end
    end)
end

-- ==============================================================================
-- 5. WAYBAR / EWW INTEGRATION (Status Output)
-- ==============================================================================

-- Outputs the current status of all monitors in JSON format.
-- Example: shader-desk-ctl "return ctl.status()"
function ctl.status()
    -- Inject the global frozen state into the JSON response
    local is_frozen = tostring(core._is_frozen == true)
    local result = string.format('{"frozen": %s, "theme": "default", ', is_frozen)
    
    -- Append primary layers for each active Wayland output
    for name, out in pairs(core.outputs) do
        local primary_tag = get_primary_tag(out) or "none"
        result = result .. string.format('"%s": {"primary_layer": "%s"}, ', name, primary_tag)
    end
    
    -- Remove the trailing comma and space to ensure strict JSON validity
    if #result > 1 then
        result = result:sub(1, -3)
    end
    
    result = result .. "}\n"
    return result
end

-- Export the module table to the global Lua environment.
-- Without this, require("ctl") returns 'true' (boolean) instead of the table,
-- causing "attempt to index global 'ctl' (a boolean value)" IPC errors.
return ctl




