// --- Auto-generated by ShaderDesk Plugin Generator ---
#include "gradient-bg.hpp"
#include "shader-utils.hpp" // ShaderDesk SDK utilities
#include <iostream>
#include <stdexcept>
#include <algorithm>

// ==============================================================================
// DEVELOPER GUIDE: EXTENDING THIS PLUGIN
// ==============================================================================
// This auto-generated file is just a starting point! You are encouraged to modify 
// It and add your own complex C++ logic.
//
// Why write C++ logic here instead of using Lua or GLSL?
// 1. High-Performance Math: Simulating physics (e.g., Boids, particles, fluid dynamics) 
//    Or generating procedural 3D meshes (like fractals) is too slow for Lua.
// 2. BlackBoard Integration: Use `core->get_blackboard()` to read zero-latency 
//    Data streams from background daemons (e.g., Audio FFT bands, raw mouse inputs).
// 3. Advanced OpenGL: You are not limited to a fullscreen triangle! You can load 
//    Textures, create Framebuffer Objects (FBOs), or dispatch Compute Shaders here.
// ==============================================================================

GradientBgEffect::GradientBgEffect() = default;

GradientBgEffect::~GradientBgEffect() {
    on_cleanup();
}

const char* GradientBgEffect::get_name() const {
    return "Gradient Bg";
}

// ------------------------------------------------------------------------------
// PARAMETER MANAGEMENT
// Exposes parameters to the Lua configuration engine.
// ------------------------------------------------------------------------------
std::vector<EffectParameter> GradientBgEffect::get_parameters() const {
    return {
        {"blend_power", "Color blend power (1.0 - hard, 3.0+ - liquid)", blend_power},
        {"bg_color", "Base background color (void)", bg_color},
        {"enable_stripes", "Enable topographic lines", enable_stripes},
        {"stripes_density", "Contour line density", stripes_density},
        {"stripes_opacity", "Contour line opacity", stripes_opacity},
        {"dithering_amount", "Anti-banding noise (color stepping)", dithering_amount},
        {"point_count", "Number of active points (0-16)", active_points}
    };
}

void GradientBgEffect::set_parameter(const std::string& name, const EffectParameterValue& value) {
    try {
        if (name == "blend_power") {
            blend_power = std::get<float>(value);
        }
        else if (name == "bg_color") {
            bg_color = std::get<glm::vec3>(value);
        }
        else if (name == "enable_stripes") {
            enable_stripes = std::get<bool>(value);
        }
        else if (name == "stripes_density") {
            stripes_density = std::get<float>(value);
        }
        else if (name == "stripes_opacity") {
            stripes_opacity = std::get<float>(value);
        }
        else if (name == "dithering_amount") {
            dithering_amount = std::get<float>(value);
        }
        else if (name == "point_count") {
            active_points = std::clamp(std::get<int>(value), 0, 16);
        }
        else {
             std::cerr << "Warning: Unknown parameter '" << name << "'." << std::endl;
        }
    } catch (const std::bad_variant_access& e) {
        std::cerr << "[" << get_name() << "] Warning: Type mismatch for parameter '" 
                  << name << "'. " << e.what() << std::endl;
    }
}

// ------------------------------------------------------------------------------
// INITIALIZATION & SHADER COMPILATION
// ------------------------------------------------------------------------------
bool GradientBgEffect::initialize(ICoreContext* core, uint32_t width, uint32_t height) {
    // [HINT] Bind your BlackBoard variables here! 
    // Example: p_audio_bands = core->get_blackboard()->bind_float_array("audio.bands", 64);

    p_positions = core->get_blackboard()->bind_float_array("grad.positions", 32); // 16 points * (x,y)
    p_colors    = core->get_blackboard()->bind_float_array("grad.colors", 48);    // 16 points * (r,g,b)
    p_radii     = core->get_blackboard()->bind_float_array("grad.radii", 16);     // 16 radii

    // 1. Load shaders from the plugin bundle directory.
    std::string vert_src = shader_utils::load_shader_source(core, get_name(), "gradient_vert.glsl");
    std::string frag_src = shader_utils::load_shader_source(core, get_name(), "gradient_frag.glsl");
    
    if (vert_src.empty() || frag_src.empty()) {
        std::cerr << "[" << get_name() << "] CRITICAL: Failed to load shader files from bundle!" << std::endl;
        return false;
    }

    program = shader_utils::create_shader_program(vert_src, frag_src);
    if (!program) {
        std::cerr << "[" << get_name() << "] CRITICAL: Shader program linking failed!" << std::endl;
        return false;
    }

    
    
    // 2. Cache uniform locations
    u_time = glGetUniformLocation(program, "time");
    u_resolution = glGetUniformLocation(program, "resolution");
    u_blend_power = glGetUniformLocation(program, "blend_power");
    u_bg_color = glGetUniformLocation(program, "bg_color");
    u_enable_stripes = glGetUniformLocation(program, "enable_stripes");
    u_stripes_density = glGetUniformLocation(program, "stripes_density");
    u_stripes_opacity = glGetUniformLocation(program, "stripes_opacity");
    u_dithering_amount = glGetUniformLocation(program, "dithering_amount");

    u_active_points = glGetUniformLocation(program, "active_points[0]");
    u_point_positions = glGetUniformLocation(program, "point_positions[0]");
    u_point_colors = glGetUniformLocation(program, "point_colors[0]");
    u_point_radii = glGetUniformLocation(program, "point_radii[0]");

    // 3. Create an empty VAO.
    // We use the "Zero-VBO Fullscreen Triangle" technique. The vertex shader 
    // Calculates vertex positions on the fly using gl_VertexID, so no VBO is needed.
    // [HINT] If you need custom 3D geometry, create your VBOs/EBOs here instead!
    glGenVertexArrays(1, &vao);
    
    std::cout << "[" << get_name() << "] Initialized successfully (Resolution: " 
              << width << "x" << height << ")." << std::endl;
    return true;
}

// ------------------------------------------------------------------------------
// MAIN RENDER LOOP
// Called by the Wayland compositor core every frame (e.g., 60 or 144 times/sec).
// ------------------------------------------------------------------------------
void GradientBgEffect::render(uint32_t width, uint32_t height, float dt) {
    // [HINT] Process your heavy CPU logic here (e.g., update particle positions) 
    // Before sending data to the GPU.
    
    glUseProgram(program);
    
    // Use the real time delta provided by the Wayland compositor for smooth animation
    time += dt; 
    
    if (u_time != -1) glUniform1f(u_time, time);
    if (u_resolution != -1) glUniform2f(u_resolution, static_cast<float>(width), static_cast<float>(height));

    glUniform1i(u_active_points, active_points);
    if (active_points > 0) {
        if (p_positions) glUniform2fv(u_point_positions, active_points, p_positions);
        if (p_colors)    glUniform3fv(u_point_colors, active_points, p_colors);
        if (p_radii)     glUniform1fv(u_point_radii, active_points, p_radii);
    }
    
    // Apply auto-generated uniform variables from Lua configuration
    glUniform1f(u_blend_power, blend_power);
    glUniform3fv(u_bg_color, 1, &bg_color[0]);
    glUniform1i(u_enable_stripes, enable_stripes);
    glUniform1f(u_stripes_density, stripes_density);
    glUniform1f(u_stripes_opacity, stripes_opacity);
    glUniform1f(u_dithering_amount, dithering_amount);

    // Disable depth testing for 2D/Background effects to prevent Z-fighting
    glDisable(GL_DEPTH_TEST);

    // ==============================================================================
    // DEFENSIVE PROGRAMMING
    // In a modular pipeline, we cannot trust the previous plugin to clean up its 
    // OpenGL state. We unbind the global VBO to ensure our "Zero-VBO" fullscreen 
    // Triangle technique doesn't crash the driver (GL_INVALID_OPERATION).
    // ==============================================================================
    glBindBuffer(GL_ARRAY_BUFFER, 0);

    // Draw the fullscreen triangle using the empty VAO
    glBindVertexArray(vao);
    glDrawArrays(GL_TRIANGLES, 0, 3);
    glBindVertexArray(0);

    // Restore depth testing for subsequent 3D layers in the rendering pipeline
    glEnable(GL_DEPTH_TEST);
}

// ------------------------------------------------------------------------------
// RESOURCE CLEANUP
// ------------------------------------------------------------------------------
void GradientBgEffect::on_cleanup() {
    if (program) {
        glDeleteProgram(program);
        program = 0;
    }
    if (vao) {
        glDeleteVertexArrays(1, &vao);
        vao = 0;
    }
}

// ==============================================================================
// C-ABI EXPORTS (Plugin Manager Entry Points)
// This guarantees stable binary compatibility between the .so and the host core.
// ==============================================================================
extern "C" {
    uint32_t get_abi_version() {
        return SHADER_DESK_ABI_VERSION;
    }
    
    IWallpaperEffectABI* create_effect() {
        return new GradientBgEffect();
    }

    void destroy_effect(IWallpaperEffectABI* effect) {
        delete static_cast<GradientBgEffect*>(effect);
    }
}
