// --- Auto-generated by generate_plugin.py ---
#ifndef GRADIENT_BG_HPP
#define GRADIENT_BG_HPP

#include "wallpaper-effect.hpp"
#include <GLES3/gl3.h>
#include <glm/glm.hpp>
#include <string>
#include <vector>

class GradientBgEffect : public WallpaperEffect {
public:
    GradientBgEffect();
    ~GradientBgEffect() override;

    // --- WallpaperEffect Interface ---
    const char* get_name() const override;
    std::vector<EffectParameter> get_parameters() const override;
    void set_parameter(const std::string& name, const EffectParameterValue& value) override;

    bool initialize(ICoreContext* core, uint32_t width, uint32_t height) override;
    void render(uint32_t width, uint32_t height, float dt) override;
    void cleanup() override;

private:
    GLuint program = 0;
    GLuint vao = 0;
    float time = 0.0f;

    // --- Parameter Member Variables ---
    float blend_power = 2.5;
    glm::vec3 bg_color = glm::vec3(0.05f, 0.05f, 0.08f);
    bool enable_stripes = false;
    float stripes_density = 15.0;
    float stripes_opacity = 0.15;
    float dithering_amount = 0.02;

    // --- Uniform Locations ---
    GLuint u_time = 0;
    GLuint u_resolution = 0;
    GLuint u_blend_power = 0;
    GLuint u_bg_color = 0;
    GLuint u_enable_stripes = 0;
    GLuint u_stripes_density = 0;
    GLuint u_stripes_opacity = 0;
    GLuint u_dithering_amount = 0;

    // --- BlackBoard Pointers ---
    float* p_positions = nullptr;
    float* p_colors = nullptr;
    float* p_radii = nullptr;
    
    // --- Array Uniforms ---
    GLuint u_active_points = 0;
    GLuint u_point_positions = 0;
    GLuint u_point_colors = 0;
    GLuint u_point_radii = 0;
    int active_points = 0; 
};

#endif // GRADIENT_BG_HPP
