// --- Auto-generated by ShaderDesk Plugin Generator ---
#include "dither-effect.hpp"
#include "shader-utils.hpp" // ShaderDesk SDK utilities
#include <iostream>
#include <stdexcept>



// ==============================================================================
// DEVELOPER GUIDE: EXTENDING THIS PLUGIN
// ==============================================================================
// This auto-generated file is just a starting point! You are encouraged to modify 
// it and add your own complex C++ logic.
//
// Why write C++ logic here instead of using Lua or GLSL?
// 1. High-Performance Math: Simulating physics (e.g., Boids, particles, fluid dynamics) 
//    or generating procedural 3D meshes (like fractals) is too slow for Lua.
// 2. BlackBoard Integration: Use `core->get_blackboard()` to read zero-latency 
//    data streams from background daemons (e.g., Audio FFT bands, raw mouse inputs).
// 3. Advanced OpenGL: You are not limited to a fullscreen triangle! You can load 
//    textures, create Framebuffer Objects (FBOs), or dispatch Compute Shaders here.
// ==============================================================================

DitherEffectEffect::DitherEffectEffect() = default;

DitherEffectEffect::~DitherEffectEffect() {
    cleanup();
}

const char* DitherEffectEffect::get_name() const {
    return "Dither Effect";
}

// ------------------------------------------------------------------------------
// PARAMETER MANAGEMENT
// Exposes parameters to the Lua configuration engine.
// ------------------------------------------------------------------------------
std::vector<EffectParameter> DitherEffectEffect::get_parameters() const {
    return {
        {"shader_theme", "Shader variation name (e.g. 'default')", active_shader},
        {"dither_spread", "Noise intensity (0.0 = banding, 1.0 = heavy noise)", dither_spread},
        {"downsample_scale", "Pixel size (1.0 = native, 4.0 = retro)", downsample_scale},
        {"bayer_size", "Bayer Matrix resolution: 0 = 2x2, 1 = 4x4, 2 = 8x8", bayer_size},
        {"colors_count", "Number of active colors in the palette (2 to 16)", colors_count},
    };
}

void DitherEffectEffect::set_parameter(const std::string& name, const EffectParameterValue& value) {
    try {
        if (name == "shader_theme") {
            std::string new_theme = std::get<std::string>(value);
            if (new_theme != active_shader) {
                active_shader = new_theme;
                needs_shader_reload = true;
            }
        }
        else if (name == "dither_spread") {
            dither_spread = std::get<float>(value);
        }
        else if (name == "downsample_scale") {
            downsample_scale = std::get<float>(value);
        }
        else if (name == "bayer_size") {
            bayer_size = std::get<int>(value);
        }
        else if (name == "colors_count") {
            colors_count = std::get<int>(value);
        }
        else {
             std::cerr << "Warning: Unknown parameter '" << name << "'." << std::endl;
        }
    } catch (const std::bad_variant_access& e) {
        std::cerr << "[" << get_name() << "] Warning: Type mismatch for parameter '" 
                  << name << "'. " << e.what() << std::endl;
    }
}

// ------------------------------------------------------------------------------
// INITIALIZATION & SHADER COMPILATION
// ------------------------------------------------------------------------------
bool DitherEffectEffect::reload_shader_program() {
    std::cout << "[" << get_name() << "] Loading shader theme: '" << active_shader << "'" << std::endl;
    
    std::string vert_src = shader_utils::load_shader_source(m_core, get_name(), active_shader + "_vert.glsl");
    std::string frag_src = shader_utils::load_shader_source(m_core, get_name(), active_shader + "_frag.glsl");
    
    // Smart Fallback: If theme-specific vertex shader is missing, use the default one
    if (vert_src.empty()) {
        vert_src = shader_utils::load_shader_source(m_core, get_name(), "dither_vert.glsl");
    }

    if (vert_src.empty() || frag_src.empty()) {
        std::cerr << "[" << get_name() << "] CRITICAL: Failed to load shaders for theme: " << active_shader << std::endl;
        return false;
    }

    GLuint new_program = shader_utils::create_shader_program(vert_src, frag_src);
    if (!new_program) {
        std::cerr << "[" << get_name() << "] CRITICAL: Shader program linking failed!" << std::endl;
        return false;
    }
    
    if (program != 0) glDeleteProgram(program);
    program = new_program;
    fetch_uniform_locations();
    
    return true;
}

void DitherEffectEffect::fetch_uniform_locations() {
    if (!program) return;
    u_time = glGetUniformLocation(program, "time");
    u_resolution = glGetUniformLocation(program, "resolution");
    u_dither_spread = glGetUniformLocation(program, "dither_spread");
    u_downsample_scale = glGetUniformLocation(program, "downsample_scale");
    u_bayer_size = glGetUniformLocation(program, "bayer_size");
    u_colors_count = glGetUniformLocation(program, "colors_count");

    u_palette = glGetUniformLocation(program, "palette");

}


bool DitherEffectEffect::initialize(ICoreContext* core, uint32_t width, uint32_t height) {
    m_core = core;

    if (!reload_shader_program()) {
        return false;
    }

    // Create an empty VAO for "Zero-VBO Fullscreen Triangle" technique.
    glGenVertexArrays(1, &vao);
    
    std::cout << "[" << get_name() << "] Initialized successfully (Resolution: " 
              << width << "x" << height << ")." << std::endl;
    return true;
}



// ------------------------------------------------------------------------------
// MAIN RENDER LOOP
// Called by the Wayland compositor core every frame (e.g., 60 or 144 times/sec).
// ------------------------------------------------------------------------------
void DitherEffectEffect::render(uint32_t width, uint32_t height, float dt) {
    if (needs_shader_reload) {
        reload_shader_program();
        needs_shader_reload = false;
    }



    glUseProgram(program);
    
    time += dt; 
    
    if (u_time != -1) glUniform1f(u_time, time);
    if (u_resolution != -1) glUniform2f(u_resolution, static_cast<float>(width), static_cast<float>(height));
    
    if (u_dither_spread != -1) glUniform1f(u_dither_spread, dither_spread);
    if (u_downsample_scale != -1) glUniform1f(u_downsample_scale, downsample_scale);
    if (u_bayer_size != -1) glUniform1i(u_bayer_size, bayer_size);
    if (u_colors_count != -1) glUniform1i(u_colors_count, colors_count);

    // ==============================================================================
    // CUSTOM LOGIC: Читаем палитру из Zero-Latency BlackBoard
    // ==============================================================================
    if (u_palette != -1) {
        // 16 цветов * 3 компоненты (RGB) = 48 float значений.
        // BlackBoard вернет указатель на статичную память O(1), никаких аллокаций!
        float* raw_palette = m_core->get_blackboard()->bind_float_array("dither.palette", 48);
        
        // Массово загружаем массив векторов в видеокарту
        glUniform3fv(u_palette, 16, raw_palette);
    }

    // Disable depth testing for 2D/Background effects to prevent Z-fighting
    glDisable(GL_DEPTH_TEST);

    glBindBuffer(GL_ARRAY_BUFFER, 0);

    // Draw the fullscreen triangle using the empty VAO
    glBindVertexArray(vao);
    glDrawArrays(GL_TRIANGLES, 0, 3);
    
    glBindVertexArray(0);
    glActiveTexture(GL_TEXTURE0);

    glEnable(GL_DEPTH_TEST);
}

// ------------------------------------------------------------------------------
// RESOURCE CLEANUP
// ------------------------------------------------------------------------------
void DitherEffectEffect::cleanup() {
    if (program) {
        glDeleteProgram(program);
        program = 0;
    }
    if (vao) {
        glDeleteVertexArrays(1, &vao);
        vao = 0;
    }

}

// ==============================================================================
// C-ABI EXPORTS (Plugin Manager Entry Points)
// ==============================================================================
extern "C" {
    uint32_t get_abi_version() {
        return SHADER_DESK_ABI_VERSION;
    }
    
    IWallpaperEffectABI* create_effect() {
        return new DitherEffectEffect();
    }

    void destroy_effect(IWallpaperEffectABI* effect) {
        delete static_cast<DitherEffectEffect*>(effect);
    }
}