// --- Auto-generated by generate_plugin.py ---
#ifndef DITHER_EFFECT_HPP
#define DITHER_EFFECT_HPP

#include "wallpaper-effect.hpp"
#include <GLES3/gl3.h>
#include <glm/glm.hpp>
#include <string>
#include <vector>

class DitherEffectEffect : public WallpaperEffect {
public:
    DitherEffectEffect();
    ~DitherEffectEffect() override;

    // --- WallpaperEffect Interface ---
    const char* get_name() const override;
    std::vector<EffectParameter> get_parameters() const override;
    void set_parameter(const std::string& name, const EffectParameterValue& value) override;

    bool initialize(ICoreContext* core, uint32_t width, uint32_t height) override;
    void render(uint32_t width, uint32_t height, float dt) override;
    void cleanup() override;

private:
    GLuint program = 0;
    GLuint vao = 0;
    float time = 0.0f;
    ICoreContext* m_core = nullptr;

    // --- Shader Theme Management ---
    std::string active_shader = "dither";
    bool needs_shader_reload = true;
    bool reload_shader_program();
    void fetch_uniform_locations();

    // --- Parameter Member Variables ---
    float dither_spread = 0.5;
    float downsample_scale = 3.0;
    int bayer_size = 1;
    int colors_count = 4;

    // --- Texture State Variables ---


    // --- Uniform Locations ---
    GLuint u_time = 0;
    GLuint u_resolution = 0;
    GLuint u_dither_spread = 0;
    GLuint u_downsample_scale = 0;
    GLuint u_bayer_size = 0;
    GLuint u_colors_count = 0;
    GLuint u_palette = 0;


};

#endif // DITHER_EFFECT_HPP