// --- Auto-generated by generate_plugin.py ---
#ifndef POSTPROCESS_EFFECT_HPP
#define POSTPROCESS_EFFECT_HPP

#include "wallpaper-effect.hpp"
#include <GLES3/gl3.h>
#include <glm/glm.hpp>
#include <string>
#include <vector>

class PostprocessEffectEffect : public WallpaperEffect {
public:
    PostprocessEffectEffect();
    ~PostprocessEffectEffect() override;

    // --- WallpaperEffect Interface ---
    const char* get_name() const override;
    std::vector<EffectParameter> get_parameters() const override;
    void set_parameter(const std::string& name, const EffectParameterValue& value) override;

    bool initialize(ICoreContext* core, uint32_t width, uint32_t height) override;
    void render(uint32_t width, uint32_t height, float dt) override;
    void on_cleanup() override;

private:
    GLuint program = 0;
    GLuint vao = 0;
    float time = 0.0f;
    ICoreContext* m_core = nullptr;

    // --- Shader Theme Management ---
    std::string active_shader = "postprocess";
    bool needs_shader_reload = true;
    bool reload_shader_program();
    void fetch_uniform_locations();

    // --- Parameter Member Variables ---
    float intensity = 0.3;
    float speed = 2.0;
    float scale = 15.0;
    int variant = 1;

    // --- Texture State Variables ---


    // --- Uniform Locations ---
    GLuint u_time = 0;
    GLuint u_resolution = 0;
    GLuint u_intensity = 0;
    GLuint u_speed = 0;
    GLuint u_scale = 0;
    GLuint u_variant = 0;


};

#endif // POSTPROCESS_EFFECT_HPP