// --- Auto-generated by ShaderDesk Plugin Generator ---
#include "postprocess-effect.hpp"
#include "shader-utils.hpp" // ShaderDesk SDK utilities
#include <iostream>
#include <stdexcept>



// ==============================================================================
// DEVELOPER GUIDE: EXTENDING THIS PLUGIN
// ==============================================================================
// This auto-generated file is just a starting point! You are encouraged to modify 
// it and add your own complex C++ logic.
//
// Why write C++ logic here instead of using Lua or GLSL?
// 1. High-Performance Math: Simulating physics (e.g., Boids, particles, fluid dynamics) 
//    or generating procedural 3D meshes (like fractals) is too slow for Lua.
// 2. BlackBoard Integration: Use `core->get_blackboard()` to read zero-latency 
//    data streams from background daemons (e.g., Audio FFT bands, raw mouse inputs).
// 3. Advanced OpenGL: You are not limited to a fullscreen triangle! You can load 
//    textures, create Framebuffer Objects (FBOs), or dispatch Compute Shaders here.
// ==============================================================================

PostprocessEffectEffect::PostprocessEffectEffect() = default;

PostprocessEffectEffect::~PostprocessEffectEffect() {
    cleanup();
}

const char* PostprocessEffectEffect::get_name() const {
    return "Postprocess Effect";
}

// ------------------------------------------------------------------------------
// PARAMETER MANAGEMENT
// Exposes parameters to the Lua configuration engine.
// ------------------------------------------------------------------------------
std::vector<EffectParameter> PostprocessEffectEffect::get_parameters() const {
    return {
        {"intensity", "Сила глитча и расслоения RGB", intensity},
        {"speed", "Скорость смены артефактов", speed},
        {"scale", "Плотность блоков глитча (чем больше, тем мельче)", scale},
        {"variant", "0: Smooth RGB, 1: Block VHS, 2: Hardcore Scanlines", variant},
    };
}

void PostprocessEffectEffect::set_parameter(const std::string& name, const EffectParameterValue& value) {
    try {
        if (name == "intensity") {
            intensity = std::get<float>(value);
        }
        else if (name == "speed") {
            speed = std::get<float>(value);
        }
        else if (name == "scale") {
            scale = std::get<float>(value);
        }
        else if (name == "variant") {
            variant = std::get<int>(value);
        }
        else {
             std::cerr << "Warning: Unknown parameter '" << name << "'." << std::endl;
        }
    } catch (const std::bad_variant_access& e) {
        std::cerr << "[" << get_name() << "] Warning: Type mismatch for parameter '" 
                  << name << "'. " << e.what() << std::endl;
    }
}

// ------------------------------------------------------------------------------
// INITIALIZATION & SHADER COMPILATION
// ------------------------------------------------------------------------------
bool PostprocessEffectEffect::initialize(ICoreContext* core, uint32_t width, uint32_t height) {
    m_core = core;

    // 1. Load shaders from the plugin bundle directory.
    std::string vert_src = shader_utils::load_shader_source(core, get_name(), "postprocess_vert.glsl");
    std::string frag_src = shader_utils::load_shader_source(core, get_name(), "postprocess_frag.glsl");
    
    if (vert_src.empty() || frag_src.empty()) {
        std::cerr << "[" << get_name() << "] CRITICAL: Failed to load shader files from bundle!" << std::endl;
        return false;
    }

    program = shader_utils::create_shader_program(vert_src, frag_src);
    if (!program) {
        std::cerr << "[" << get_name() << "] CRITICAL: Shader program linking failed!" << std::endl;
        return false;
    }
    
    // 2. Cache uniform locations
    u_time = glGetUniformLocation(program, "time");
    u_resolution = glGetUniformLocation(program, "resolution");
    u_intensity = glGetUniformLocation(program, "intensity");
    u_speed = glGetUniformLocation(program, "speed");
    u_scale = glGetUniformLocation(program, "scale");
    u_variant = glGetUniformLocation(program, "variant");

    // 3. Create an empty VAO.
    // We use the "Zero-VBO Fullscreen Triangle" technique.
    glGenVertexArrays(1, &vao);
    
    std::cout << "[" << get_name() << "] Initialized successfully (Resolution: " 
              << width << "x" << height << ")." << std::endl;
    return true;
}



// ------------------------------------------------------------------------------
// MAIN RENDER LOOP
// Called by the Wayland compositor core every frame (e.g., 60 or 144 times/sec).
// ------------------------------------------------------------------------------
void PostprocessEffectEffect::render(uint32_t width, uint32_t height, float dt) {


    glUseProgram(program);
    
    // Use the real time delta provided by the Wayland compositor for smooth animation
    time += dt; 
    
    if (u_time != -1) glUniform1f(u_time, time);
    if (u_resolution != -1) glUniform2f(u_resolution, static_cast<float>(width), static_cast<float>(height));
    
    // Apply auto-generated uniform variables from Lua configuration
    if (u_intensity != -1) glUniform1f(u_intensity, intensity);
    if (u_speed != -1) glUniform1f(u_speed, speed);
    if (u_scale != -1) glUniform1f(u_scale, scale);
    if (u_variant != -1) glUniform1i(u_variant, variant);

    // Bind textures and resolutions


    // Disable depth testing for 2D/Background effects to prevent Z-fighting
    glDisable(GL_DEPTH_TEST);

    glBindBuffer(GL_ARRAY_BUFFER, 0);

    // Draw the fullscreen triangle using the empty VAO
    glBindVertexArray(vao);
    glDrawArrays(GL_TRIANGLES, 0, 3);
    
    glBindVertexArray(0);
    glActiveTexture(GL_TEXTURE0);

    // Restore depth testing for subsequent 3D layers in the rendering pipeline
    glEnable(GL_DEPTH_TEST);
}

// ------------------------------------------------------------------------------
// RESOURCE CLEANUP
// ------------------------------------------------------------------------------
void PostprocessEffectEffect::cleanup() {
    if (program) {
        glDeleteProgram(program);
        program = 0;
    }
    if (vao) {
        glDeleteVertexArrays(1, &vao);
        vao = 0;
    }

}

// ==============================================================================
// C-ABI EXPORTS (Plugin Manager Entry Points)
// ==============================================================================
extern "C" {
    uint32_t get_abi_version() {
        return SHADER_DESK_ABI_VERSION;
    }
    
    IWallpaperEffectABI* create_effect() {
        return new PostprocessEffectEffect();
    }

    void destroy_effect(IWallpaperEffectABI* effect) {
        delete static_cast<PostprocessEffectEffect*>(effect);
    }
}