# Cmake/embed_resource.cmake
# Read the contents of the source file (e.g., ctl.lua)
file(READ "${INPUT_FILE}" CONTENT)

# Write it out as a C++ header
file(WRITE "${OUTPUT_FILE}" "// Auto-generated by CMake. DO NOT EDIT.\n#pragma once\n\n")
file(APPEND "${OUTPUT_FILE}" "namespace Embedded {\n")
# Use LUA_EOF as a delimiter so internal Lua quotes don't break C++
file(APPEND "${OUTPUT_FILE}" "inline constexpr const char* ${VAR_NAME} = R\"LUA_EOF(\n${CONTENT})LUA_EOF\";\n")
file(APPEND "${OUTPUT_FILE}" "} // Namespace Embedded\n")