# cmake/embed_resource.cmake
# Читаем содержимое исходного файла (напр., ctl.lua)
file(READ "${INPUT_FILE}" CONTENT)

# Записываем его в виде C++ заголовка
file(WRITE "${OUTPUT_FILE}" "// Auto-generated by CMake. DO NOT EDIT.\n#pragma once\n\n")
file(APPEND "${OUTPUT_FILE}" "namespace Embedded {\n")
# Используем LUA_EOF как разделитель, чтобы кавычки внутри Lua не ломали C++
file(APPEND "${OUTPUT_FILE}" "inline constexpr const char* ${VAR_NAME} = R\"LUA_EOF(\n${CONTENT})LUA_EOF\";\n")
file(APPEND "${OUTPUT_FILE}" "} // namespace Embedded\n")