// --- Auto-generated by generate_plugin.py ---
#ifndef IMAGE_BG_HPP
#define IMAGE_BG_HPP

#include "wallpaper-effect.hpp"
#include <GLES3/gl3.h>
#include <glm/glm.hpp>
#include <string>
#include <vector>
#include <thread>
#include <atomic>
#include <mutex>

class ImageBgEffect : public WallpaperEffect {
public:
    ImageBgEffect();
    ~ImageBgEffect() override;

    // --- WallpaperEffect Interface ---
    const char* get_name() const override;
    std::vector<EffectParameter> get_parameters() const override;
    void set_parameter(const std::string& name, const EffectParameterValue& value) override;

    bool initialize(ICoreContext* core, uint32_t width, uint32_t height) override;
    void render(uint32_t width, uint32_t height, float dt) override;
    void cleanup() override;

private:
    GLuint program = 0;
    GLuint vao = 0;
    float time = 0.0f;
    ICoreContext* m_core = nullptr;

    // --- Parameter Member Variables ---
    int fill_mode = 0;
    float scale = 1.0;
    glm::vec2 offset = glm::vec2(0.0f, 0.0f);
    float rotation = 0.0;
    float brightness = 1.0;
    float contrast = 1.0;
    float saturation = 1.0;
    glm::vec3 tint_color = glm::vec3(0.0f, 0.0f, 0.0f);
    float tint_intensity = 0.0;
    float blur_radius = 0.0;
    
    // Dynamic Resolution & Optimization
    bool optimize_vram = true;       // Use 16-bit textures
    bool dynamic_lod = true;         // Auto-scale VRAM usage based on screen scale
    int max_texture_size = 8192;     // Absolute hardware limit

    // --- Texture State Variables ---
    GLuint base_image_id = 0;
    std::string base_image_path = "";
    std::string loaded_texture_key = ""; // Format: "path_resolution"
    bool base_image_pending = false;
    float base_image_w = 1.0f;
    float base_image_h = 1.0f;
    int current_vram_res = 0;        // Max dimension currently loaded in VRAM

    // --- Asynchronous Loading (Zero-Latency Epoll) ---
    std::atomic<bool> is_loading{false};
    std::atomic<bool> abort_load{false};
    std::mutex async_mutex;
    std::thread worker_thread;
    
    // Payload from worker to main thread
    unsigned char* async_data = nullptr;
    int async_w = 0, async_h = 0, async_c = 0;
    std::string async_path = "";
    int async_target_res = 0;

    // --- Uniform Locations ---
    GLuint u_time = 0, u_resolution = 0, u_fill_mode = 0, u_scale = 0;
    GLuint u_offset = 0, u_rotation = 0, u_brightness = 0, u_contrast = 0;
    GLuint u_saturation = 0, u_tint_color = 0, u_tint_intensity = 0;
    GLuint u_blur_radius = 0, u_base_image = 0, u_base_image_resolution = 0;

    void process_textures(uint32_t screen_w, uint32_t screen_h);
    void release_current_texture();
    void start_async_load(const std::string& path, int target_res);
    void check_async_results();
};

#endif // IMAGE_BG_HPP