// --- Auto-generated by ShaderDesk Plugin Generator ---
#include "image-bg.hpp"
#include "shader-utils.hpp" 
#include <iostream>
#include <stdexcept>
#include <unordered_map>

#define STB_IMAGE_IMPLEMENTATION
#include "stb_image.h"

// ==============================================================================
// SHARED TEXTURE POOL WITH DYNAMIC LOD
// Cache keys format: "filepath_resolution" (e.g., "img1.png_2048")
// ==============================================================================
struct SharedTexture {
    GLuint id = 0;
    float w = 1.0f;
    float h = 1.0f;
    int res = 0;
    int ref_count = 0;
};
static std::unordered_map<std::string, SharedTexture> s_texture_pool;

ImageBgEffect::ImageBgEffect() = default;

ImageBgEffect::~ImageBgEffect() {
    // Gracefully shut down the background thread
    abort_load = true;
    if (worker_thread.joinable()) {
        worker_thread.join();
    }
    on_cleanup();
}

const char* ImageBgEffect::get_name() const { return "Image Bg"; }

std::vector<EffectParameter> ImageBgEffect::get_parameters() const {
    return {
        {"fill_mode", "0: Cover, 1: Contain, 2: Stretch, 3: Tile", fill_mode},
        {"scale", "Image scale (Zoom)", scale},
        {"offset", "UV Offset (Pan X/Y)", offset},
        {"rotation", "Rotation in degrees", rotation},
        {"brightness", "Brightness multiplier", brightness},
        {"contrast", "Contrast adjustment", contrast},
        {"saturation", "Color saturation (0.0 = Grayscale)", saturation},
        {"tint_color", "Tint color (RGB)", tint_color},
        {"tint_intensity", "Tint blending intensity (0.0 - 1.0)", tint_intensity},
        {"blur_radius", "Gaussian blur intensity", blur_radius},
        {"base_image_path", "Main background image", base_image_path},
        {"optimize_vram", "Use 16-bit texture formats to halve VRAM usage", optimize_vram},
        {"dynamic_lod", "Auto-scale VRAM resolution based on Lua scale", dynamic_lod},
        {"max_texture_size", "Absolute hardware limit for textures", max_texture_size}
    };
}

void ImageBgEffect::set_parameter(const std::string& name, const EffectParameterValue& value) {
    try {
        if (name == "fill_mode") fill_mode = std::get<int>(value);
        else if (name == "scale") scale = std::get<float>(value);
        else if (name == "offset") offset = std::get<glm::vec2>(value);
        else if (name == "rotation") rotation = std::get<float>(value);
        else if (name == "brightness") brightness = std::get<float>(value);
        else if (name == "contrast") contrast = std::get<float>(value);
        else if (name == "saturation") saturation = std::get<float>(value);
        else if (name == "tint_color") tint_color = std::get<glm::vec3>(value);
        else if (name == "tint_intensity") tint_intensity = std::get<float>(value);
        else if (name == "blur_radius") blur_radius = std::get<float>(value);
        else if (name == "optimize_vram") optimize_vram = std::get<bool>(value);
        else if (name == "dynamic_lod") dynamic_lod = std::get<bool>(value);
        else if (name == "max_texture_size") max_texture_size = std::get<int>(value);
        else if (name == "base_image_path") {
            std::string new_path = std::get<std::string>(value);
            if (new_path != base_image_path) {
                base_image_path = new_path;
                base_image_pending = true;
            }
        }
    } catch (const std::bad_variant_access& e) {}
}

bool ImageBgEffect::initialize(ICoreContext* core, uint32_t width, uint32_t height) {
    m_core = core;

    std::string vert_src = shader_utils::load_shader_source(core, get_name(), "image_vert.glsl");
    std::string frag_src = shader_utils::load_shader_source(core, get_name(), "image_frag.glsl");
    if (vert_src.empty() || frag_src.empty()) return false;

    program = shader_utils::create_shader_program(vert_src, frag_src);
    if (!program) return false;
    
    u_time = glGetUniformLocation(program, "time");
    u_resolution = glGetUniformLocation(program, "resolution");
    u_fill_mode = glGetUniformLocation(program, "fill_mode");
    u_scale = glGetUniformLocation(program, "scale");
    u_offset = glGetUniformLocation(program, "offset");
    u_rotation = glGetUniformLocation(program, "rotation");
    u_brightness = glGetUniformLocation(program, "brightness");
    u_contrast = glGetUniformLocation(program, "contrast");
    u_saturation = glGetUniformLocation(program, "saturation");
    u_tint_color = glGetUniformLocation(program, "tint_color");
    u_tint_intensity = glGetUniformLocation(program, "tint_intensity");
    u_blur_radius = glGetUniformLocation(program, "blur_radius");
    u_base_image = glGetUniformLocation(program, "base_image");
    u_base_image_resolution = glGetUniformLocation(program, "base_image_resolution");

    glGenVertexArrays(1, &vao);
    return true;
}

void ImageBgEffect::release_current_texture() {
    if (!loaded_texture_key.empty()) {
        auto it = s_texture_pool.find(loaded_texture_key);
        if (it != s_texture_pool.end()) {
            it->second.ref_count--;
            if (it->second.ref_count <= 0) {
                glDeleteTextures(1, &it->second.id);
                s_texture_pool.erase(it);
            }
        }
        loaded_texture_key = "";
        base_image_id = 0;
        current_vram_res = 0;
    }
}

// ==============================================================================
// CPU BILINEAR DOWNSAMPLER
// ==============================================================================
static void cpu_downscale_bilinear(unsigned char*& data, int& w, int& h, int channels, int max_dim) {
    if (w <= max_dim && h <= max_dim) return;

    float ratio = std::min((float)max_dim / w, (float)max_dim / h);
    int nw = static_cast<int>(w * ratio);
    int nh = static_cast<int>(h * ratio);

    unsigned char* ndata = (unsigned char*)malloc(nw * nh * channels);
    if (!ndata) return; 

    for (int y = 0; y < nh; ++y) {
        for (int x = 0; x < nw; ++x) {
            float gx = x / ratio;
            float gy = y / ratio;
            int gxi = static_cast<int>(gx);
            int gyi = static_cast<int>(gy);
            
            float tx = gx - gxi;
            float ty = gy - gyi;
            float c00 = (1 - tx) * (1 - ty);
            float c10 = tx * (1 - ty);
            float c01 = (1 - tx) * ty;
            float c11 = tx * ty;

            for (int c = 0; c < channels; ++c) {
                int p00 = data[(gyi * w + gxi) * channels + c];
                int p10 = (gxi + 1 < w) ? data[(gyi * w + gxi + 1) * channels + c] : p00;
                int p01 = (gyi + 1 < h) ? data[((gyi + 1) * w + gxi) * channels + c] : p00;
                int p11 = ((gxi + 1 < w) && (gyi + 1 < h)) ? data[((gyi + 1) * w + gxi + 1) * channels + c] : p00;

                float val = p00 * c00 + p10 * c10 + p01 * c01 + p11 * c11;
                ndata[(y * nw + x) * channels + c] = static_cast<unsigned char>(std::min(std::max(val, 0.0f), 255.0f));
            }
        }
    }
    
    stbi_image_free(data);
    data = ndata;
    w = nw;
    h = nh;
}

// ==============================================================================
// ASYNCHRONOUS WORKER
// ==============================================================================
void ImageBgEffect::start_async_load(const std::string& path, int target_res) {
    if (is_loading) return; 
    
    if (worker_thread.joinable()) worker_thread.join();

    is_loading = true;
    abort_load = false;

    worker_thread = std::thread([this, path, target_res]() {
        // ИСПРАВЛЕНИЕ: Отключаем аппаратный флип, так как он уже есть в image_vert.glsl
        stbi_set_flip_vertically_on_load(false); 
        
        int w, h, c;
        unsigned char* d = stbi_load(path.c_str(), &w, &h, &c, 0); 
        
        if (abort_load) {
            if (d) stbi_image_free(d);
            is_loading = false;
            return;
        }

        if (d) {
            cpu_downscale_bilinear(d, w, h, c, target_res);
            
            std::lock_guard<std::mutex> lock(async_mutex);
            if (async_data) free(async_data); 
            
            async_data = d;
            async_w = w;
            async_h = h;
            async_c = c;
            async_path = path;
            async_target_res = target_res;
        } else {
            std::cerr << "[Image Bg] Async load failed for: " << path << std::endl;
        }

        is_loading = false;
    });
}

// ==============================================================================
// MAIN THREAD SYNC POINT
// ==============================================================================
void ImageBgEffect::check_async_results() {
    std::lock_guard<std::mutex> lock(async_mutex);
    if (!async_data) return; 

    std::string new_key = async_path + "_" + std::to_string(async_target_res);
    release_current_texture(); 

    glGenTextures(1, &base_image_id);
    glBindTexture(GL_TEXTURE_2D, base_image_id);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_CLAMP_TO_EDGE);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_CLAMP_TO_EDGE);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR_MIPMAP_LINEAR);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);

    GLenum format = (async_c == 3) ? GL_RGB : GL_RGBA;
    GLenum internal_format = (async_c == 3) ? GL_RGB8 : GL_RGBA8;
    
    // ИСПРАВЛЕНИЕ КОРРУПЦИИ: Исходные данные от процессора ВСЕГДА 8-битные!
    GLenum type = GL_UNSIGNED_BYTE;

    // Оптимизация VRAM: Заставляем видеокарту сжать 8-битные данные в 16 бит
    if (optimize_vram) {
        internal_format = (async_c == 3) ? GL_RGB565 : GL_RGBA4;
    }

    glPixelStorei(GL_UNPACK_ALIGNMENT, 1); 
    glTexImage2D(GL_TEXTURE_2D, 0, internal_format, async_w, async_h, 0, format, type, async_data);
    glGenerateMipmap(GL_TEXTURE_2D);
    glPixelStorei(GL_UNPACK_ALIGNMENT, 4);

    base_image_w = static_cast<float>(async_w);
    base_image_h = static_cast<float>(async_h);
    current_vram_res = async_target_res;
    loaded_texture_key = new_key;

    s_texture_pool[new_key] = {base_image_id, base_image_w, base_image_h, current_vram_res, 1};
    
    // Очистка оперативной памяти
    free(async_data); 
    async_data = nullptr;
}


void ImageBgEffect::process_textures(uint32_t screen_w, uint32_t screen_h) {
    if (!m_core || base_image_path.empty()) return;

    int required_res = max_texture_size; 
    
    if (dynamic_lod) {
        // Улучшенный расчет требуемого качества:
        // Если картинка занимает лишь часть экрана (Contain), учитываем scale.
        // Если это фон (Cover), scale не добавляет физических пикселей на монитор.
        float needed_pixels = std::max(screen_w, screen_h);
        if (fill_mode == 1) needed_pixels *= scale; 
        
        int lod_tiers[] = {256, 512, 1024, 2048, 4096, 8192, 16384};
        for (int tier : lod_tiers) {
            if (tier >= needed_pixels) {
                required_res = tier;
                break;
            }
        }
    }
    required_res = std::min(required_res, max_texture_size);

    std::string fp = base_image_path;
    if (fp[0] != '/') {
        const char* bundle_path = m_core->get_bundle_path(get_name());
        if (bundle_path && bundle_path[0] != '\0') fp = std::string(bundle_path) + "/" + fp;
    }

    std::string target_key = fp + "_" + std::to_string(required_res);

    if (base_image_pending || (target_key != loaded_texture_key)) {
        auto it = s_texture_pool.find(target_key);
        if (it != s_texture_pool.end()) {
            release_current_texture();
            it->second.ref_count++;
            base_image_id = it->second.id;
            base_image_w = it->second.w;
            base_image_h = it->second.h;
            current_vram_res = it->second.res;
            loaded_texture_key = target_key;
            base_image_pending = false;
            return;
        }

        if (!is_loading) {
            start_async_load(fp, required_res);
            base_image_pending = false;
        }
    }

    check_async_results();
}

void ImageBgEffect::render(uint32_t width, uint32_t height, float dt) {
    process_textures(width, height);
    time += dt; 

    if (!base_image_id) return;

    glUseProgram(program);
    if (u_time != -1) glUniform1f(u_time, time);
    if (u_resolution != -1) glUniform2f(u_resolution, static_cast<float>(width), static_cast<float>(height));
    if (u_fill_mode != -1) glUniform1i(u_fill_mode, fill_mode);
    if (u_scale != -1) glUniform1f(u_scale, scale);
    if (u_offset != -1) glUniform2fv(u_offset, 1, &offset[0]);
    if (u_rotation != -1) glUniform1f(u_rotation, rotation);
    if (u_brightness != -1) glUniform1f(u_brightness, brightness);
    if (u_contrast != -1) glUniform1f(u_contrast, contrast);
    if (u_saturation != -1) glUniform1f(u_saturation, saturation);
    if (u_tint_color != -1) glUniform3fv(u_tint_color, 1, &tint_color[0]);
    if (u_tint_intensity != -1) glUniform1f(u_tint_intensity, tint_intensity);
    if (u_blur_radius != -1) glUniform1f(u_blur_radius, blur_radius);

    glActiveTexture(GL_TEXTURE0);
    glBindTexture(GL_TEXTURE_2D, base_image_id);
    if (u_base_image != -1) glUniform1i(u_base_image, 0);
    if (u_base_image_resolution != -1) glUniform2f(u_base_image_resolution, base_image_w, base_image_h);

    glDisable(GL_DEPTH_TEST);
    glBindVertexArray(vao);
    glDrawArrays(GL_TRIANGLE_STRIP, 0, 4); 
    glBindVertexArray(0);
    glActiveTexture(GL_TEXTURE0);
    glEnable(GL_DEPTH_TEST);
}

void ImageBgEffect::on_cleanup() {
    if (program) { glDeleteProgram(program); program = 0; }
    if (vao) { glDeleteVertexArrays(1, &vao); vao = 0; }
    release_current_texture(); 
}

extern "C" {
    uint32_t get_abi_version() { return SHADER_DESK_ABI_VERSION; }
    IWallpaperEffectABI* create_effect() { return new ImageBgEffect(); }
    void destroy_effect(IWallpaperEffectABI* effect) { delete static_cast<ImageBgEffect*>(effect); }
}